### ISSUE TITLE
Tasks for ops 2.1 release

### ISSUE THREAD

**Issue by benhoyt** [canonical/operator#884]
For the ops 2.1 release, we'd like to add a couple of new APIs and do a bit of code cleanup:

* [x] Add API support for `open-port` et al: https://github.com/canonical/operator/issues/179
* [x] Use f-strings (Python 3.6+) everywhere: https://github.com/canonical/operator/pull/889
* [x] Use variable type annotations (Python 3.6+) instead of `# type: T` comments: https://github.com/canonical/operator/pull/904
* [ ] Refactor large files into directories (but be careful that it's API-compatible!)
* [ ] Consider moving a curated set of names to the `ops` top-level. See https://github.com/canonical/operator/issues/731
* [x] Un-vendor websockets library (it was only vendored as latest doesn't work in Python 3.5): https://github.com/canonical/operator/pull/891
* [x] Update versions of Pyright and lock versions of other dependencies: https://github.com/canonical/operator/pull/894
* [ ] ~Consider making ops a "namespace package" so we can exclude testing by default. See https://github.com/canonical/operator/issues/865#issuecomment-1370635292~

See also [tasks for ops 2.0 release issue](https://github.com/canonical/operator/issues/865).

**Comment by tinvaan** [comment]
Hi @benhoyt, have tried to address the last two items on the release checklist.

- https://github.com/canonical/operator/pull/891
- https://github.com/tinvaan/operator/pull/1

The changes need a bit of polishing and thorough testing. Happy to iron them out and ready them for the 2.1 release.

**Comment by sed-i** [comment]
I keep finding namespaced status painfully missing
https://github.com/canonical/operator/issues/665

**Comment by benhoyt** [comment]
For the record, I moved "Add bytes API for Secrets: https://github.com/canonical/operator/issues/869" off this list. It's interesting but definitely doesn't seem to be high priority.

**Comment by benhoyt** [comment]
@sed-i FYI, I've added the namespaced/scope status bullet point under a new draft [Tasks for ops 2.2 release](https://github.com/canonical/operator/issues/906) issue.

**Comment by benhoyt** [comment]
I've thought further about "namespace packages", and I'm going to pass on those for now. We can revisit this later, or consider something like `pip install ops[scenario]` when `ops-scenario` stabilized and if we decide to promote that as the native approach to testing charms.

**Comment by benhoyt** [comment]
Closing this now that 2.1.0 is released: https://github.com/canonical/operator/releases/tag/2.1.0

I started work on these two items, but will move them to the [2.2.0 task list](https://github.com/canonical/operator/issues/906) to finish:

* Refactor large files into directories (but be careful that it's API-compatible!)
* Consider moving a curated set of names to the ops top-level. See https://github.com/canonical/operator/issues/731
